// ============================================================================
// Sample Data Definitions for JD Labs Interview Platform
// ============================================================================

// Helper function to generate dates in the past
const daysAgo = (days, hours = 0, minutes = 0) => {
  const date = new Date();
  date.setDate(date.getDate() - days);
  date.setHours(date.getHours() - hours);
  date.setMinutes(date.getMinutes() - minutes);
  return date.toISOString();
};

// ============================================================================
// LANGUAGES
// ============================================================================

const languages = [
  { name: 'English', code: 'en', is_active: true },
  { name: 'Spanish', code: 'es', is_active: true },
  { name: 'French', code: 'fr', is_active: true },
  { name: 'German', code: 'de', is_active: true },
  { name: 'Mandarin Chinese', code: 'zh', is_active: true },
  { name: 'Japanese', code: 'ja', is_active: true },
  { name: 'Hindi', code: 'hi', is_active: true },
  { name: 'Portuguese', code: 'pt', is_active: true },
  { name: 'Arabic', code: 'ar', is_active: true },
  { name: 'Russian', code: 'ru', is_active: true },
];

// ============================================================================
// JOBS
// ============================================================================

const jobs = [
  {
    title: 'Senior Frontend Engineer',
    description: 'Build scalable, performant web applications using React 19, TypeScript, and modern frontend tooling. Lead frontend architecture decisions and mentor junior developers.',
    company_name: 'TechCorp Inc',
    location: 'San Francisco, CA (Remote)',
    employment_type: 'Full-time',
    salary_range: '$140,000 - $180,000',
    requirements: [
      '5+ years of React experience',
      'Expert in TypeScript and modern ES6+',
      'Strong understanding of state management (Redux, Zustand, Context API)',
      'Experience with performance optimization and code splitting',
      'Familiarity with testing frameworks (Jest, React Testing Library)',
    ],
    is_active: true,
  },
  {
    title: 'Backend Engineer - Node.js',
    description: 'Design and implement RESTful APIs and microservices using Node.js, Express, and PostgreSQL. Build scalable backend systems for millions of users.',
    company_name: 'DataFlow Systems',
    location: 'Austin, TX (Hybrid)',
    employment_type: 'Full-time',
    salary_range: '$130,000 - $160,000',
    requirements: [
      '4+ years Node.js development',
      'Strong SQL and database design skills',
      'Experience with Docker and Kubernetes',
      'Knowledge of event-driven architectures',
      'API security best practices',
    ],
    is_active: true,
  },
  {
    title: 'Full-Stack Developer',
    description: 'Work across the entire stack from React frontend to Node.js/PostgreSQL backend. Own features end-to-end in a fast-paced startup environment.',
    company_name: 'StartupHub',
    location: 'New York, NY',
    employment_type: 'Full-time',
    salary_range: '$120,000 - $150,000',
    requirements: [
      '3+ years full-stack experience',
      'React and Node.js proficiency',
      'Database design (PostgreSQL, MongoDB)',
      'RESTful API development',
      'Git version control',
    ],
    is_active: true,
  },
  {
    title: 'DevOps Engineer',
    description: 'Build and maintain CI/CD pipelines, manage cloud infrastructure on AWS, and ensure system reliability. Work with Docker, Kubernetes, and Infrastructure as Code.',
    company_name: 'CloudScale Inc',
    location: 'Seattle, WA (Remote)',
    employment_type: 'Full-time',
    salary_range: '$135,000 - $170,000',
    requirements: [
      '3+ years DevOps experience',
      'Strong AWS knowledge (EC2, RDS, S3, Lambda)',
      'Docker and Kubernetes expertise',
      'CI/CD pipeline development',
      'Infrastructure as Code (Terraform, CloudFormation)',
    ],
    is_active: true,
  },
  {
    title: 'Mobile Developer - React Native',
    description: 'Build cross-platform mobile applications using React Native. Implement native modules and optimize for performance on iOS and Android.',
    company_name: 'MobileFirst Apps',
    location: 'Boston, MA (Hybrid)',
    employment_type: 'Full-time',
    salary_range: '$125,000 - $155,000',
    requirements: [
      '4+ years React Native experience',
      'Native iOS/Android development knowledge',
      'App Store/Play Store deployment',
      'Redux or MobX state management',
      'RESTful API integration',
    ],
    is_active: true,
  },
  {
    title: 'Data Scientist',
    description: 'Develop machine learning models for predictive analytics. Work with large datasets using Python, scikit-learn, and TensorFlow.',
    company_name: 'AI Innovations',
    location: 'San Jose, CA',
    employment_type: 'Full-time',
    salary_range: '$145,000 - $185,000',
    requirements: [
      'PhD or Masters in Computer Science/Statistics',
      '3+ years ML experience',
      'Python (pandas, scikit-learn, TensorFlow)',
      'SQL and big data tools (Spark, Hadoop)',
      'Statistical modeling and A/B testing',
    ],
    is_active: true,
  },
  {
    title: 'Machine Learning Engineer',
    description: 'Build production ML systems and pipelines. Deploy models at scale using MLOps best practices.',
    company_name: 'DeepTech Labs',
    location: 'Palo Alto, CA (Remote)',
    employment_type: 'Full-time',
    salary_range: '$155,000 - $200,000',
    requirements: [
      '5+ years ML engineering',
      'PyTorch/TensorFlow expertise',
      'MLOps and model deployment',
      'Distributed training experience',
      'Cloud platforms (AWS SageMaker, GCP AI Platform)',
    ],
    is_active: true,
  },
  {
    title: 'QA Automation Engineer',
    description: 'Design and implement automated test frameworks. Ensure software quality through comprehensive testing strategies.',
    company_name: 'QualityFirst Software',
    location: 'Denver, CO',
    employment_type: 'Full-time',
    salary_range: '$100,000 - $130,000',
    requirements: [
      '3+ years QA automation',
      'Selenium, Cypress, or Playwright',
      'JavaScript/TypeScript',
      'CI/CD integration',
      'API testing (Postman, Rest Assured)',
    ],
    is_active: true,
  },
  {
    title: 'Product Manager (Technical)',
    description: 'Drive product strategy and roadmap for technical products. Work closely with engineering teams to deliver customer value.',
    company_name: 'ProductVision Inc',
    location: 'Chicago, IL (Hybrid)',
    employment_type: 'Full-time',
    salary_range: '$130,000 - $165,000',
    requirements: [
      '5+ years product management',
      'Technical background (CS degree or engineering experience)',
      'Data-driven decision making',
      'Agile/Scrum methodologies',
      'Stakeholder management',
    ],
    is_active: true,
  },
  {
    title: 'UI/UX Designer',
    description: 'Create beautiful, intuitive user interfaces. Conduct user research and design systems for web and mobile applications.',
    company_name: 'DesignStudio Co',
    location: 'Los Angeles, CA',
    employment_type: 'Full-time',
    salary_range: '$110,000 - $140,000',
    requirements: [
      '4+ years UI/UX design',
      'Figma, Sketch, Adobe XD',
      'Design systems and component libraries',
      'User research and usability testing',
      'HTML/CSS knowledge (bonus)',
    ],
    is_active: true,
  },
  {
    title: 'Cloud Architect (AWS)',
    description: 'Design cloud-native architectures on AWS. Lead cloud migration projects and optimize infrastructure costs.',
    company_name: 'CloudExperts LLC',
    location: 'Dallas, TX (Remote)',
    employment_type: 'Full-time',
    salary_range: '$160,000 - $200,000',
    requirements: [
      '7+ years cloud architecture',
      'AWS Solutions Architect certification',
      'Microservices and serverless',
      'Cost optimization strategies',
      'Security and compliance',
    ],
    is_active: true,
  },
  {
    title: 'Security Engineer',
    description: 'Implement security best practices and conduct vulnerability assessments. Protect systems from cyber threats.',
    company_name: 'SecureNet Solutions',
    location: 'Washington, DC',
    employment_type: 'Full-time',
    salary_range: '$140,000 - $175,000',
    requirements: [
      '5+ years security engineering',
      'Penetration testing experience',
      'OWASP Top 10 knowledge',
      'Security certifications (CISSP, CEH)',
      'Incident response',
    ],
    is_active: true,
  },
  {
    title: 'Site Reliability Engineer (SRE)',
    description: 'Ensure system reliability, performance, and scalability. Build monitoring and alerting systems.',
    company_name: 'ReliableOps Inc',
    location: 'Portland, OR (Remote)',
    employment_type: 'Full-time',
    salary_range: '$145,000 - $180,000',
    requirements: [
      '4+ years SRE experience',
      'Kubernetes and Docker',
      'Monitoring tools (Prometheus, Grafana)',
      'Incident management',
      'Performance tuning',
    ],
    is_active: true,
  },
  {
    title: 'Content Strategist',
    description: 'Develop content strategies for digital products. Create compelling narratives and manage content lifecycle.',
    company_name: 'ContentFirst Media',
    location: 'Miami, FL (Hybrid)',
    employment_type: 'Full-time',
    salary_range: '$85,000 - $110,000',
    requirements: [
      '3+ years content strategy',
      'SEO and content marketing',
      'CMS experience (WordPress, Contentful)',
      'Analytics (Google Analytics)',
      'Strong writing skills',
    ],
    is_active: true,
  },
  {
    title: 'Engineering Manager',
    description: 'Lead and mentor engineering teams. Drive technical excellence and foster a collaborative culture.',
    company_name: 'TechLeaders Corp',
    location: 'San Francisco, CA',
    employment_type: 'Full-time',
    salary_range: '$170,000 - $220,000',
    requirements: [
      '7+ years engineering experience',
      '3+ years management',
      'Technical leadership',
      'Team building and mentoring',
      'Agile methodologies',
    ],
    is_active: true,
  },
];

// ============================================================================
// INTERVIEW QUESTIONS BY POSITION
// ============================================================================

const questionsByPosition = {
  'Senior Frontend Engineer': [
    'Tell me about your experience with React and modern frontend frameworks.',
    'Explain the difference between useState and useReducer hooks. When would you use each?',
    'How do you approach performance optimization in React applications?',
    'Describe your experience with state management libraries like Redux or Zustand.',
    'Walk me through how you would implement code splitting and lazy loading.',
    "What's your approach to testing React components?",
    'How do you handle accessibility in web applications?',
  ],
  'Backend Engineer - Node.js': [
    'Describe your experience designing RESTful APIs.',
    'How do you handle database transactions and ensure data integrity?',
    'Explain the difference between horizontal and vertical scaling.',
    "What's your approach to API security and authentication?",
    'How do you design microservices architecture?',
    'Describe your experience with caching strategies.',
  ],
  'Full-Stack Developer': [
    'Tell me about a full-stack feature you built from scratch.',
    'How do you decide between SQL and NoSQL databases?',
    'Explain how you handle authentication in a full-stack application.',
    'What are your strategies for maintaining code quality across the stack?',
    'Describe your experience with deployment and DevOps.',
  ],
  'DevOps Engineer': [
    'Walk me through your CI/CD pipeline setup.',
    'How do you approach infrastructure as code?',
    'Describe your experience with Docker and Kubernetes.',
    'What monitoring and logging tools have you used?',
    'How do you handle production incidents?',
    'Explain your approach to cloud cost optimization.',
  ],
  'Data Scientist': [
    'Explain the machine learning workflow you typically follow.',
    "What's the difference between supervised and unsupervised learning?",
    'How do you handle imbalanced datasets?',
    'Describe your experience with feature engineering.',
    'What metrics do you use to evaluate model performance?',
    'How do you explain complex models to non-technical stakeholders?',
  ],
  'QA Automation Engineer': [
    'Describe your approach to building test automation frameworks.',
    'How do you decide what to automate vs. test manually?',
    'What are the key qualities of good automated tests?',
    'Explain your experience with CI/CD integration for tests.',
    'How do you handle flaky tests?',
  ],
  'Mobile Developer - React Native': [
    'Describe your experience with React Native.',
    'How do you handle platform-specific code in React Native?',
    'What strategies do you use for mobile app performance optimization?',
    'Explain your approach to handling app state in mobile applications.',
    'How do you test React Native applications?',
  ],
  'UI/UX Designer': [
    'Walk me through your design process from research to final mockups.',
    'How do you approach creating a design system?',
    'Describe a time when user research changed your design direction.',
    'How do you balance aesthetics with usability?',
    'What tools do you use for prototyping and why?',
  ],
  'Content Strategist': [
    'Describe your approach to developing a content strategy.',
    'How do you measure content performance?',
    'Explain how you optimize content for SEO.',
    'How do you manage content across multiple channels?',
    'Describe your experience with content management systems.',
  ],
};

// Default questions for positions not in the map
const defaultQuestions = [
  'Tell me about your relevant experience for this role.',
  'What are your key strengths and how do they apply to this position?',
  'Describe a challenging project you worked on and how you approached it.',
  'How do you stay current with new technologies and industry trends?',
  'Where do you see yourself in the next 3-5 years?',
];

// ============================================================================
// INTERVIEW DATA
// ============================================================================

const interviews = [
  {
    candidate_name: 'Emma Davis',
    position: 'Senior Frontend Engineer',
    mode: 'Video Interview',
    language: 'English',
    difficulty: 'Hard',
    status: 'completed',
    days_ago: 6,
    duration_minutes: 35,
    overall_score: 92,
    has_video: true,
    malpractice_report: null,
  },
  {
    candidate_name: 'James Wilson',
    position: 'Backend Engineer - Node.js',
    mode: 'Video Interview',
    language: 'English',
    difficulty: 'Medium',
    status: 'completed',
    days_ago: 5,
    duration_minutes: 28,
    overall_score: 73,
    has_video: true,
    malpractice_report: '[10:12:30] Screen Switch: Candidate switched tabs for 8 seconds.\n[10:18:45] Long Pause: Silence detected for 18 seconds.',
  },
  {
    candidate_name: 'Alex Martinez',
    position: 'QA Automation Engineer',
    mode: 'Audio Interview',
    language: 'English',
    difficulty: 'Easy',
    status: 'completed',
    days_ago: 4,
    duration_minutes: 22,
    overall_score: 81,
    has_video: true,
    malpractice_report: null,
  },
  {
    candidate_name: 'Sophia Lee',
    position: 'Data Scientist',
    mode: 'Chat Interview',
    language: 'English',
    difficulty: 'Hard',
    status: 'in_progress',
    days_ago: 0,
    duration_minutes: null,
    overall_score: null,
    has_video: false,
    malpractice_report: null,
  },
  {
    candidate_name: 'David Kim',
    position: 'DevOps Engineer',
    mode: 'Live Share Interview',
    language: 'English',
    difficulty: 'Medium',
    status: 'lobby',
    days_ago: 0,
    duration_minutes: null,
    overall_score: null,
    has_video: false,
    malpractice_report: null,
  },
  {
    candidate_name: 'Linda Brown',
    position: 'Machine Learning Engineer',
    mode: 'Video Interview',
    language: 'English',
    difficulty: 'Hard',
    status: 'completed',
    days_ago: 9,
    duration_minutes: 35,
    overall_score: 58,
    has_video: true,
    malpractice_report: null,
  },
  {
    candidate_name: 'Roberto Garcia',
    position: 'Full-Stack Developer',
    mode: 'Audio Interview',
    language: 'Spanish',
    difficulty: 'Medium',
    status: 'completed',
    days_ago: 8,
    duration_minutes: 28,
    overall_score: 78,
    has_video: true,
    malpractice_report: null,
  },
  {
    candidate_name: 'Priya Sharma',
    position: 'Mobile Developer - React Native',
    mode: 'Video Interview',
    language: 'Hindi',
    difficulty: 'Medium',
    status: 'completed',
    days_ago: 7,
    duration_minutes: 30,
    overall_score: 88,
    has_video: true,
    malpractice_report: null,
  },
  {
    candidate_name: 'Thomas Anderson',
    position: 'Cloud Architect (AWS)',
    mode: 'Video Interview',
    language: 'English',
    difficulty: 'Hard',
    status: 'cancelled',
    days_ago: 3,
    duration_minutes: null,
    overall_score: null,
    has_video: false,
    malpractice_report: null,
  },
  {
    candidate_name: 'Yuki Tanaka',
    position: 'UI/UX Designer',
    mode: 'Chat Interview',
    language: 'Japanese',
    difficulty: 'Easy',
    status: 'completed',
    days_ago: 10,
    duration_minutes: 18,
    overall_score: 84,
    has_video: false,
    malpractice_report: null,
  },
  {
    candidate_name: 'Maria Silva',
    position: 'Security Engineer',
    mode: 'Video Interview',
    language: 'Portuguese',
    difficulty: 'Hard',
    status: 'completed',
    days_ago: 12,
    duration_minutes: 38,
    overall_score: 68,
    has_video: true,
    malpractice_report: '[10:08:15] Topic Diversion: Off-topic discussion detected.\n[10:25:30] Screen Switch: Multiple tab switches (3 instances).',
  },
  {
    candidate_name: 'Ahmed Hassan',
    position: 'Site Reliability Engineer (SRE)',
    mode: 'Audio Interview',
    language: 'Arabic',
    difficulty: 'Medium',
    status: 'completed',
    days_ago: 11,
    duration_minutes: 34,
    overall_score: 79,
    has_video: true,
    malpractice_report: null,
  },
  {
    candidate_name: 'Chen Wei',
    position: 'Product Manager (Technical)',
    mode: 'Video Interview',
    language: 'Mandarin Chinese',
    difficulty: 'Medium',
    status: 'lobby',
    days_ago: 0,
    duration_minutes: null,
    overall_score: null,
    has_video: false,
    malpractice_report: null,
  },
  {
    candidate_name: 'Sophie Laurent',
    position: 'Engineering Manager',
    mode: 'Video Interview',
    language: 'French',
    difficulty: 'Hard',
    status: 'completed',
    days_ago: 13,
    duration_minutes: 42,
    overall_score: 90,
    has_video: true,
    malpractice_report: null,
  },
  {
    candidate_name: 'Dmitri Volkov',
    position: 'Content Strategist',
    mode: 'Video Interview',
    language: 'Russian',
    difficulty: 'Easy',
    status: 'in_progress',
    days_ago: 0,
    duration_minutes: null,
    overall_score: null,
    has_video: false,
    malpractice_report: null,
  },
  {
    candidate_name: 'Isabella Romano',
    position: 'Full-Stack Developer',
    mode: 'Chat Interview',
    language: 'English',
    difficulty: 'Medium',
    status: 'completed',
    days_ago: 14,
    duration_minutes: 25,
    overall_score: 72,
    has_video: false,
    malpractice_report: null,
  },
  {
    candidate_name: 'Hans Schmidt',
    position: 'DevOps Engineer',
    mode: 'Video Interview',
    language: 'German',
    difficulty: 'Hard',
    status: 'completed',
    days_ago: 15,
    duration_minutes: 32,
    overall_score: 94,
    has_video: true,
    malpractice_report: null,
  },
  {
    candidate_name: 'Olivia Johnson',
    position: 'Senior Frontend Engineer',
    mode: 'Live Share Interview',
    language: 'English',
    difficulty: 'Medium',
    status: 'completed',
    days_ago: 16,
    duration_minutes: 33,
    overall_score: 86,
    has_video: false,
    malpractice_report: null,
  },
  {
    candidate_name: 'Ethan Williams',
    position: 'Backend Engineer - Node.js',
    mode: 'Audio Interview',
    language: 'English',
    difficulty: 'Hard',
    status: 'completed',
    days_ago: 17,
    duration_minutes: 40,
    overall_score: 63,
    has_video: true,
    malpractice_report: null,
  },
  {
    candidate_name: 'Ava Martinez',
    position: 'Data Scientist',
    mode: 'Chat Interview',
    language: 'English',
    difficulty: 'Hard',
    status: 'lobby',
    days_ago: 0,
    duration_minutes: null,
    overall_score: null,
    has_video: false,
    malpractice_report: null,
  },
];

// ============================================================================
// HELPER: Generate sample answers based on score
// ============================================================================

const generateAnswer = (question, score) => {
  const answers = {
    excellent: [
      `I have extensive experience with this topic. In my previous role, I implemented several solutions that directly address this. For example, I built a system that handled over 1 million requests per day using modern best practices. The key considerations were scalability, maintainability, and performance. I'd be happy to walk you through my approach in detail.`,
      `Great question! This is an area I'm particularly passionate about. I've worked on multiple projects where this was critical. My approach typically involves analyzing requirements, evaluating trade-offs, and selecting the most appropriate solution. I've found that communication with stakeholders and iterative development are key to success.`,
      `I have deep knowledge in this area from both academic study and practical application. I've implemented this in production environments serving millions of users. The architecture I designed used industry-standard patterns while optimizing for our specific use case. I also mentored junior developers on these concepts.`,
    ],
    good: [
      `I have solid experience with this. I've worked on several projects that required this skill. While I haven't encountered every edge case, I'm confident in my understanding of the core concepts and best practices. I'm always eager to learn more and stay current with new developments.`,
      `Yes, I'm familiar with this topic. In my current role, I use this regularly. I understand the fundamentals well and have successfully implemented solutions. There's always more to learn, but I feel comfortable tackling challenges in this area.`,
      `I have good working knowledge of this. I've used it in production environments and understand the key principles. I may not know every advanced technique, but I know how to research and learn when needed.`,
    ],
    average: [
      `I have some experience with this from my previous work. I understand the basics and have used it a few times. I'd need to review some details for more complex scenarios, but I can get up to speed quickly.`,
      `I'm somewhat familiar with this concept. I've studied it and used it in a few projects. I'd say I have a foundational understanding, though I could certainly deepen my knowledge with more hands-on experience.`,
      `I know the basics of this topic. I've read about it and tried it in some personal projects. I think with more practice and real-world application, I could become more proficient.`,
    ],
    below: [
      `I've heard of this but don't have much practical experience. I understand some of the basic concepts from reading documentation. It's an area I'd like to learn more about.`,
      `I'm not very experienced with this particular topic. I know it exists and what it's generally used for, but I haven't had many opportunities to work with it directly.`,
      `This is not an area where I have deep knowledge. I'm familiar with the terminology but would need guidance and training to be effective with it.`,
    ],
  };

  let category;
  if (score >= 85) category = 'excellent';
  else if (score >= 75) category = 'good';
  else if (score >= 60) category = 'average';
  else category = 'below';

  const answerOptions = answers[category];
  return answerOptions[Math.floor(Math.random() * answerOptions.length)];
};

module.exports = {
  languages,
  jobs,
  interviews,
  questionsByPosition,
  defaultQuestions,
  generateAnswer,
  daysAgo,
};
